name: Deployment
on:
  push:
    branches:
     - main

#  created:
#      tags:
#        - "v*"

#  workflow_run:
#    workflows: ["Haskell-CI"]
#    types:
#      - completed

env:
  TAILWIND_VERSION: 3.0.18
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  GHC_STATIC_OPTIONS: "-static -optl-static -optl-pthread -fPIC"
  GHC_OPTIONS: "-threaded -rtsopts -with-rtsopts=-N"

jobs:
  create-release:
    name: Release with stack ${{ matrix.stack }} / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.7.3"]
        ghc: ["8.10.7"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download TailwindCSS standalone CLI
        run: |
          curl \
            -sL https://github.com/tailwindlabs/tailwindcss/releases/download/v${{ env.TAILWIND_VERSION }}/tailwindcss-linux-x64 \
            -o tailwindcss
          chmod +x tailwindcss
          ./tailwindcss --help

      - name: Build and minify stylesheet
        run: |
          mkdir -p ./swoogle/priv/static/assets/
          ./tailwindcss --input ./swoogle/assets/app.css \
            --output ./swoogle/priv/static/assets/app.css \
            --config ./swoogle/assets/tailwind.config.js \
            --minify

      - name: Setup GHC ${{ matrix.ghc }} and Stack ${{ matrix.stack }}
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: ${{ matrix.stack }}
          stack-setup-ghc: true

      - name: Install dependencies
        run: |
          stack build --only-dependencies

      - name: Build swoogle
        run: |
          stack build swapi:exe:swoogle --copy-bins

      - name: Cache stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-stack

      - name: Bundle swoogle
        run: |
          mkdir -p artifact
          cp ~/.local/bin/swoogle ./artifact/swoogle-bin
          cp -r ./swoogle/priv ./artifact/swoogle/
          zip -r swoogle-linux.zip artifact

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: swoogle-linux
          path: swoogle-linux.zip

#      - name: Create release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: ~/.local/bin/swoogle

# deploy-swoogle:
#   name: Deploy swoogle to Fly.io
#   runs-on: ubuntu-latest
#   if: ${{ github.event.workflow_run.conclusion == 'success' }}

#   steps:
#     - name: Checkout repo
#       uses: actions/checkout@v2

#     - name: Download TailwindCSS standalone CLI
#       run: |
#         # GitHub bin path:
#         # https://github.community/t/adding-a-binary-to-the-path-from-a-docker-github-action-for-use-by-later-workflow-steps/16922/2
#         curl \
#           -sL https://github.com/tailwindlabs/tailwindcss/releases/download/v${{ env.TAILWIND_VERSION }}/tailwindcss-linux-x64 \
#           -o tailwindcss
#         chmod +x tailwindcss
#         ./tailwindcss --help

#     - name: Build and minify stylesheet
#       run: |
#         mkdir -p ./swoogle/priv/static/assets/

#         ./tailwindcss --input ./swoogle/assets/app.css \
#           --output ./swoogle/priv/static/assets/app.css \
#           --config ./swoogle/assets/tailwind.config.js \
#           --minify

#     - name: Deploy with flyctl
#       uses: superfly/flyctl-actions@1.3
#       with:
#         args: "deploy --local-only"
