name: CD
on:
  push:
    branches:
     - main
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  create-release:
    name: Build release and deploy to Fly.io
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy with flyctl
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --local-only"

#      Future stuff
#      - name: Create release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: ~/.local/bin/swoogle
