# References:
# - https://kodimensional.dev/github-actions
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: cabal ${{ matrix.cabal }} / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cabal: ["3.6.2.0"]
        ghc: ["8.10.7"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup GHC ${{ matrix.ghc }} and Cabal ${{ matrix.cabal }}
        uses: haskell/actions/setup@v1.2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Freeze Cabal plan
        run: cabal freeze --project-file=cabal.project.local

      - uses: actions/cache@v2
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal build all --only-dependencies --project-file=cabal.project.local

      - name: Build
        run: |
          cabal build all --project-file=cabal.project.local

      - name: Test
        run: |
          cabal test all --project-file=cabal.project.local

      - name: Documentation
        run: |
          cabal haddock --project-file=cabal.project.local

  deploy:
    name: Build release and deploy to Fly.io
    runs-on: ubuntu-20.04
    needs: [build-and-test]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build swoogle-server
        run: |
          docker run \
            --volume $PWD:/mnt \
            utdemir/ghc-musl:v23-ghc8107 \
            /mnt/bin/build-static

      - name: What's in here?
        run: |
          sudo apt install tree
          tree .

      - name: Send off to Fly.io
        uses: superfly/flyctl-actions@1.3
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy --local-only"
