# Reference: https://kodimensional.dev/github-actions
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # FIXME: YEAH I CAVED AND MOVED BACK TO CABAL. NOW I GOTTA FIX THIS
  build-and-test:
    name: cabal ${{ matrix.cabal }} / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.6.2.0"]
        ghc: ["8.10.7"]

    steps:
      # https://raehik.github.io/2021/03/01/caching-stack-and-cabal-haskell-builds-on-github-actions.html
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set all tracked file modification times to the time of their last commit
        run: |
          rev=HEAD
          for f in $(git ls-tree -r -t --full-name --name-only "$rev") ; do
              touch -d $(git log --pretty=format:%cI -1 "$rev" -- "$f") "$f";
          done

      - name: Setup GHC ${{ matrix.ghc }} and Cabal ${{ matrix.cabal }}
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Freeze Cabal plan
        run: cabal freeze

      - name: Cache Cabal build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-build-env.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-${{ matrix.ghc }}

      # TODO: Include benchmarks if ever I do end up writing some
      # --bench --no-run-benchmarks
      - name: Install dependencies
        run: |
          cabal build \
            --only-dependencies \
            --enable-tests

      - name: Build
        run: |
          cabal build

      - name: Test
        run: |
          cabal test
