# References:
# - https://kodimensional.dev/github-actions
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: cabal ${{ matrix.cabal }} / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.6.2.0"]
        ghc: ["8.10.7"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup GHC ${{ matrix.ghc }} and Cabal ${{ matrix.cabal }}
        uses: haskell/actions/setup@v1.2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure
        run: |
          cabal configure --enable-tests --enable-benchmarks --enable-documentation --test-show-details=direct --write-ghc-environment-files=always

      - name: Freeze Cabal plan
        run: cabal freeze

      - uses: actions/cache@v2
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal build all --only-dependencies

      - name: Build
        run: |
          cabal build all

      - name: Test
        run: |
          cabal test all

      - name: Documentation
        run: |
          cabal haddock

  deploy:
    name: Build release and deploy to Fly.io
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        cabal: ["3.6.2.0"]
        ghc: ["8.10.7"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup GHC ${{ matrix.ghc }} and Cabal ${{ matrix.cabal }}
        id: setup-haskell-cabal
        uses: haskell/actions/setup@v1.2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure
        run: |
          cabal configure --enable-documentation

      - name: Freeze Cabal plan
        run: cabal freeze

      - uses: actions/cache@v2
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal build all --only-dependencies

      - name: Install dynamic libs
        run: |
            sudo apt-get install -y software-properties-common
            sudo apt-get install -y build-essential pkg-config curl libffi-dev libffi6 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5
            sudo apt-get install -y libsodium-dev sqlite zlib1g-dev libssl-dev
            rm -rf /var/lib/apt/lists/*

      - name: Build swoogle-server
        run: |
          cabal install swapi:exe:swoogle-server \
            --enable-optimization=2 \
            --enable-split-sections \
            --enable-executable-stripping \
            --enable-library-stripping \
            --ghc-option=-threaded \
            --ghc-option=-rtsopts \
            --ghc-option=-with-rtsopts=-N \
            --install-method=copy \
            --installdir=.

      - name: What's in here?
        run: |
          sudo apt install tree
          tree .

      - name: Send off to Fly.io
        uses: superfly/flyctl-actions@1.3
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy --local-only"
