# Reference: https://kodimensional.dev/github-actions
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # FIXME: YEAH I CAVED AND MOVED BACK TO CABAL. NOW I GOTTA FIX THIS
  build-and-test:
    name: cabal ${{ matrix.cabal }} / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.6.2.0"]
        ghc: ["8.10.7"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup GHC ${{ matrix.ghc }} and Cabal ${{ matrix.cabal }}
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      # TODO: Include benchmarks if ever I do end up writing some
      # --bench --no-run-benchmarks
      - name: Install dependencies
        run: |
          cabal build \
            --only-dependencies \
            --enable-tests

      - name: Build
        run: |
          cabal build

      - name: Test
        run: |
          cabal test
