name: Haskell Deploy
on:
  push:
#    branches:
#      - main

#  workflow_run:
#    workflows: ["Haskell-CI"]
#    types:
#      - completed

env:
  TAILWIND_VERSION: 3.0.18
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-swoogle:
    name: Deploy swoogle to Fly.io
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download TailwindCSS standalone CLI
        run: |
          # GitHub bin path:
          # https://github.community/t/adding-a-binary-to-the-path-from-a-docker-github-action-for-use-by-later-workflow-steps/16922/2
          curl \
            -sL https://github.com/tailwindlabs/tailwindcss/releases/download/v${{ env.TAILWIND_VERSION }}/tailwindcss-linux-x64 \
            -o tailwindcss
          chmod +x tailwindcss
          ./tailwindcss --help

      - name: Build and minify stylesheet
        run: |
          mkdir -p ./swoogle/priv/static/assets/

          ./tailwindcss --input ./swoogle/assets/app.css \
            --output ./swoogle/priv/static/assets/app.css \
            --config ./swoogle/assets/tailwind.config.js \
            --minify

      - name: Deploy with flyctl
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --local-only"
